project:
  type: website

website:
  title: "Oligotrophic Mesozooplankton Methods Comparison"
  navbar:
    background: dark
    search: false
    right:
      - href: index.qmd
        text: Home
      - text: "Main Analyses"
        menu:
        - href: main_analysis_01.qmd
          text: Size Distributions
        - href: main_analysis_02.qmd
          text: Relative Abundance
      - text: 'Supplemental'
        menu: 
          - href: supp_analysis_01.qmd
            text: Full Size Range Comparison

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    css: styles.css

editor: visual

