# Source all for main analysis
rm(list = ls())
source('./R/mgmt_01_mocness-formatting.R')
source('./R/main_analysis_01_size-distribution-plots.R')
source('./R/main_analysis_02_rel-abundance.R')
source('./R/mgmt_03_moc_binned-density.R')
source('./R/mgmt_03_uvp_binned-density.R')
source('./R/main_analysis_04_density-regression.R')
source('./R/mgmt_05_abundance_depth_integration.R')
source('./R/main_analysis_05_depth-integration.R')
source('./R/mgmt_06_moc_binned-biomass.R')
source('./R/mgmt_06_uvp_binned-biomass.R')
source('./R/main_analysis_06_biomass-depth-profiles.R')
source('./R/main_analysis_07_biomass-regression.R')
source('./R/mgmt_08_biomass_depth_integration.R')
source('./R/main_analysis_08_biomass_depth-integration.R')
rm(list = ls())
